name: workmanagement
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter        
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  fl_chart: ^0.71.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0
  logger: ^2.5.0
  uuid: ^4.4.0
  collection: ^1.18.0
  file_picker: ^10.1.2
  table_calendar: ^3.1.3
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  assets:
  - assets/icons/
  uses-material-design: true