// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_S9LbXhCO5OlWuyomecsaJTycNafvFGY',
    appId: '1:362988978831:android:49355f5c486769eb55a6fa',
    messagingSenderId: '362988978831',
    projectId: 'mobileapp-33dc4',
    storageBucket: 'mobileapp-33dc4.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBEaYnmO2QGghJPtJZBgY_LILkYdaNOpE',
    appId: '1:362988978831:web:2b5f92e9606e788555a6fa',
    messagingSenderId: '362988978831',
    projectId: 'mobileapp-33dc4',
    authDomain: 'mobileapp-33dc4.firebaseapp.com',
    storageBucket: 'mobileapp-33dc4.firebasestorage.app',
    measurementId: 'G-Y3HTZQB17V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1h_BFUZyCUak2bdg2TzYsJ-JGyPeB0wU',
    appId: '1:362988978831:ios:6c42cca09a6c82cd55a6fa',
    messagingSenderId: '362988978831',
    projectId: 'mobileapp-33dc4',
    storageBucket: 'mobileapp-33dc4.firebasestorage.app',
    androidClientId: '362988978831-jj9p8duef6adaa22h2fptlu53stgrred.apps.googleusercontent.com',
    iosClientId: '362988978831-g8ng57gujc20t7b7tmko2pjrqisbqe7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.workmanagement',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1h_BFUZyCUak2bdg2TzYsJ-JGyPeB0wU',
    appId: '1:362988978831:ios:6c42cca09a6c82cd55a6fa',
    messagingSenderId: '362988978831',
    projectId: 'mobileapp-33dc4',
    storageBucket: 'mobileapp-33dc4.firebasestorage.app',
    androidClientId: '362988978831-jj9p8duef6adaa22h2fptlu53stgrred.apps.googleusercontent.com',
    iosClientId: '362988978831-g8ng57gujc20t7b7tmko2pjrqisbqe7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.workmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBEaYnmO2QGghJPtJZBgY_LILkYdaNOpE',
    appId: '1:362988978831:web:b0639de23dd7e40455a6fa',
    messagingSenderId: '362988978831',
    projectId: 'mobileapp-33dc4',
    authDomain: 'mobileapp-33dc4.firebaseapp.com',
    storageBucket: 'mobileapp-33dc4.firebasestorage.app',
    measurementId: 'G-NG17BG6DCP',
  );

}